name: Build

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      projectPath:
        required: false
        default: .
        type: string

jobs:
  build-all-target-platforms:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore library cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          buildName: ${{ inputs.projectName }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload build
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ inputs.projectName }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}